alarm_panel_eventlog:
  name: Retrieve Event Log
  description: Retrieve the Alarm Panel Event Log.
  fields:
    code:
      name: User Code
      description: An optional code to send to the panel.
      example: "1234"
    panel:
      name: Panel Id
      description: An optional panel number, use 0 for single panel in use
      example: "0"
    
alarm_panel_command:
  name: Send Command
  description: Send a command to the Alarm Panel.
  fields:
    command:
      description: "The command to send to the panel"
      example: 'disarm'
    code:
      description: An optional code to send to the panel.
      example: "1234"
    panel:
      name: Panel Id
      description: An optional panel number, defaults to 0 for when a single panel is in use
      example: "0"

alarm_panel_reconnect:
  name: Panel Reconnection
  description: Reconnect to the Alarm Panel following a previous problem.
  fields:
    panel:
      name: Panel Id
      description: An optional panel number, use 0 for single panel in use
      example: "0"

alarm_sensor_bypass:
  name: Sensor Bypass
  description: Bypass a visonic sensor.
  fields:
    entity_id:
      description: Name of the visonic sensor to bypass. This is case sensitive.
      example: 'binary_sensor.visonic_z02'
    bypass:
      description: An optional bypass ("True") or stop the bypass and re-arm ("False"), defaults to False
      example: "False"
    code:
      description: An optional code to send to the panel.
      example: "1234"
    panel:
      name: Panel Id
      description: An optional panel number, use 0 for single panel in use
      example: "0"
